---

- name: Teardown Environment

  hosts: local

  vars_files:
    - vars/aws-config.yml

  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that: 
          - "ansible_version.major == 2"
          - "ansible_version.minor == 4"
        msg: "This script is only supported with the 2.4 version of Ansible"

    # - fail: msg="Variable '{{ item }}' is not defined or is empty"
    #   when: (deployment_type == 'openshift-enterprise') and ((item not in vars) or vars[item] == '')
    #   with_items: 
    #     - rhsm_username
    #     - rhsm_password
    #     - rhsm_pool

  post_tasks:
    - name: Completed
      debug:
        msg: 'Finished tearing down environment {{namespace}}'

  roles:
  - teardown-virtual-machines
  - teardown-security-groups
  - teardown-vpc
  - teardown-dns